# Generated by Django 4.1.3 on 2023-04-17 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0004_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
