# Generated by Django 4.1.3 on 2023-03-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_year', models.PositiveIntegerField()),
                ('genres', models.CharField(max_length=200)),
            ],
        ),
    ]
